name=ESP32WiFiProvisioner
version=1.0.3
author=Vijayanand R
maintainer=Vijayanand R
sentence=ESP32 WiFi captive portal provisioning library with extensible custom fields
paragraph=ESP32WiFiProvisioner provides a lightweight WiFi Access Point captive portal for Arduino ESP32 projects. It always collects WiFi SSID and password, while allowing users to add custom configuration fields dynamically via a clean callback-based API.
category=Communication
url=https://github.com/VijayGES/ESP32WiFiProvisioner
architectures=esp32,esp8266

